import { access, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);
const repoRoot = path.resolve(__dirname, "..");
const outputPath = path.join(repoRoot, "rules.js");

const FETCH_HEADERS = {
  "User-Agent": "Mozilla/5.0 (compatible; MAPE-Calculator-Updater/1.0)",
  "Accept-Language": "ja,en;q=0.9",
};

const SOURCE_URLS = {
  ripeNetworkInfo: "https://stat.ripe.net/data/network-info/data.json",
  ripePrefixOverview: "https://stat.ripe.net/data/prefix-overview/data.json",
  ripeAsOverview: "https://stat.ripe.net/data/as-overview/data.json",
};

async function fetchJson(baseUrl, resource) {
  const url = `${baseUrl}?resource=${encodeURIComponent(resource)}`;
  const response = await fetch(url, { headers: FETCH_HEADERS });
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status}`);
  }
  return response.json();
}

async function loadExistingData() {
  try {
    await access(outputPath);
    delete require.cache[require.resolve(outputPath)];
    return require(outputPath);
  } catch (error) {
    return null;
  }
}

function normalizeRuleSourceDate(serviceId, sourceDate) {
  if (serviceId === "ocn") {
    return sourceDate || "2026年1月 OCN 公開ルール";
  }
  return "同梱ルールスナップショット";
}

function sanitizeRule(serviceId, rule) {
  return {
    service: rule.service,
    ruleIpv6Prefix: rule.ruleIpv6Prefix,
    ruleIpv6PrefixLength: rule.ruleIpv6PrefixLength,
    ruleIpv4Prefix: rule.ruleIpv4Prefix,
    ruleIpv4PrefixLength: rule.ruleIpv4PrefixLength,
    eaLength: rule.eaLength,
    psidOffset: rule.psidOffset,
    brAddress: rule.brAddress,
    sourceDate: normalizeRuleSourceDate(serviceId, rule.sourceDate),
    region: rule.region || null,
  };
}

function sanitizeService(service) {
  const rules = (service.rules || []).map((rule) => sanitizeRule(service.id, rule));
  const result = {
    id: service.id,
    name: service.name,
    vne: service.vne,
    representativeIsps: service.representativeIsps || [],
    supportedIsps: service.supportedIsps || [],
    portCount: service.portCount,
    sharedUsers: service.sharedUsers,
    addressRangeSummary: service.addressRangeSummary,
    representativePrefixQuery: service.representativePrefixQuery,
    brAddresses: service.brAddresses || [],
    rules,
    ruleSourceDate: normalizeRuleSourceDate(
      service.id,
      service.ruleSourceDate || rules[0]?.sourceDate
    ),
  };

  if (service.v6plusDetails) {
    result.v6plusDetails = service.v6plusDetails;
  }

  if (service.bgp) {
    result.bgp = {
      originAsn: service.bgp.originAsn,
      originHolder: service.bgp.originHolder,
      brOriginPrefix: service.bgp.brOriginPrefix,
      representativeBgpPrefix: service.bgp.representativeBgpPrefix,
      lookupUrls: service.bgp.lookupUrls || [],
      brAddresses: service.bgp.brAddresses || [],
    };
  }

  return result;
}

async function buildBgpMetadata(service) {
  const enrichedBrAddresses = [];

  for (const br of service.brAddresses) {
    const networkInfo = await fetchJson(SOURCE_URLS.ripeNetworkInfo, br.address);
    enrichedBrAddresses.push({
      label: br.label,
      address: br.address,
      originPrefix: networkInfo.data.prefix,
      lookupUrls: [
        {
          label: "RIPEstat",
          url: `https://stat.ripe.net/resource/${encodeURIComponent(br.address)}`,
        },
        {
          label: "BGP HE",
          url: `https://bgp.he.net/ip/${br.address}`,
        },
      ],
    });
  }

  const primaryBr = enrichedBrAddresses[0];
  const networkInfo = await fetchJson(SOURCE_URLS.ripeNetworkInfo, primaryBr.address);
  const prefixOverview = await fetchJson(
    SOURCE_URLS.ripePrefixOverview,
    service.representativePrefixQuery
  );
  const originAsn = Number(networkInfo.data.asns[0]);
  const asOverview = await fetchJson(SOURCE_URLS.ripeAsOverview, `AS${originAsn}`);

  return {
    originAsn: `AS${originAsn}`,
    originHolder: asOverview.data.holder,
    brOriginPrefix: networkInfo.data.prefix,
    representativeBgpPrefix: prefixOverview.data.resource,
    lookupUrls: [
      {
        label: "RIPEstat AS",
        url: `https://stat.ripe.net/resource/AS${originAsn}`,
      },
      {
        label: "BGP HE AS",
        url: `https://bgp.he.net/AS${originAsn}`,
      },
      {
        label: "RIPEstat Prefix",
        url: `https://stat.ripe.net/resource/${encodeURIComponent(service.representativePrefixQuery)}`,
      },
    ],
    brAddresses: enrichedBrAddresses,
  };
}

function buildOutput(data) {
  return `// This file is generated by scripts/update-rules.mjs. Do not edit manually.\n(function (global) {\n  "use strict";\n\n  const data = ${JSON.stringify(data, null, 2)};\n\n  global.MAPE_RULES_DATA = data;\n\n  if (typeof module !== "undefined" && module.exports) {\n    module.exports = data;\n  }\n})(typeof window !== "undefined" ? window : globalThis);\n`;
}

function buildComparableData(data) {
  return {
    calculationSourceNote: data.calculationSourceNote,
    services: data.services.map((service) => sanitizeService(service)),
  };
}

async function main() {
  const existingData = await loadExistingData();
  if (!existingData || !Array.isArray(existingData.services)) {
    throw new Error("Existing rules.js could not be loaded.");
  }

  const services = existingData.services.map((service) => sanitizeService(service));

  for (const service of services) {
    service.bgp = await buildBgpMetadata(service);
  }

  const output = {
    generatedAt: new Date().toISOString(),
    calculationSourceNote:
      "RIPEstat / BGP HE の情報は AS / BR の参考情報です。",
    services,
  };

  const comparableOutput = JSON.stringify(buildComparableData(output));
  const comparableExisting = existingData ? JSON.stringify(buildComparableData(existingData)) : null;

  if (comparableExisting === comparableOutput && existingData?.generatedAt) {
    output.generatedAt = existingData.generatedAt;
  }

  await writeFile(outputPath, buildOutput(output), "utf8");

  if (comparableExisting === comparableOutput) {
    console.log("No rule changes detected in rules.js");
  } else {
    console.log("Updated rules.js");
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
